//! Runtime SRT wire-encryption state (gh #208).
//!
//! SRT AES encryption used to be controlled solely by the `SRT_INGEST_PASSPHRASE`
//! / `SRT_PLAYBACK_PASSPHRASE` env vars, read once at startup by both the backend
//! and OME (`Server.xml` `${env:...}`) — so flipping it meant editing `.env` and
//! restarting the whole stack. This module makes the passphrase **DB-managed**
//! (the `settings` table) and toggleable from the admin Stream Keys tab.
//!
//! OME still only reads its SRT passphrase at process startup (v0.20.5 can't
//! hot-reload `Server.xml`; its REST API rejects bind changes), so applying a
//! change is unavoidably an **OME restart**. To bridge that: the backend writes
//! the current passphrase to `<data>/srt.env`; the `ome_start.sh` wrapper sources
//! that file before launching OME, and the toggle handler restarts the `ome`
//! supervisor program. A restart drops every stream briefly and is a hard cutover
//! (all encoders/players must switch to the new passphrase) — surfaced in the UI.
//!
//! Source of truth: the `settings` table (no `.env` involvement — the admin
//! toggle owns it entirely).

use crate::credentials as cred;
use crate::error::AppError;
use rand::RngExt;
use std::io::Write;
use std::os::unix::fs::OpenOptionsExt;

pub const KEY_ENABLED: &str = "srt_encryption_enabled";
pub const KEY_INGEST_PASSPHRASE: &str = "srt_ingest_passphrase";
pub const KEY_PLAYBACK_PASSPHRASE: &str = "srt_playback_passphrase";

/// SRT AES key length in bytes (`SRTO_PBKEYLEN`). Fixed at 16 (AES-128); the
/// combined admin toggle generates the passphrases, so there is no need to
/// expose the key length.
pub const PBKEYLEN: u32 = 16;

/// Effective SRT encryption config, resolved from the DB. Passphrases are `None`
/// whenever encryption is disabled, so callers never advertise a stale secret.
pub struct EffectiveSrt {
    pub enabled: bool,
    pub ingest_passphrase: Option<String>,
    pub playback_passphrase: Option<String>,
    pub pbkeylen: u32,
}

/// A fresh random SRT passphrase: 32 hex chars, comfortably inside libsrt's
/// 10–79 range and free of shell-special characters (it is written into
/// `srt.env` and sourced by `ome_start.sh`).
fn gen_passphrase() -> String {
    let bytes: [u8; 16] = rand::rng().random();
    bytes.iter().map(|b| format!("{:02x}", b)).collect()
}

/// Resolve the effective SRT encryption config from the DB. Absent flag ⇒
/// disabled (a fresh install starts unencrypted; the admin enables it).
pub fn resolve(conn: &rusqlite::Connection) -> EffectiveSrt {
    let enabled = cred::settings_get(conn, KEY_ENABLED).as_deref() == Some("1");
    EffectiveSrt {
        enabled,
        ingest_passphrase: enabled
            .then(|| cred::settings_get(conn, KEY_INGEST_PASSPHRASE))
            .flatten()
            .filter(|s| !s.is_empty()),
        playback_passphrase: enabled
            .then(|| cred::settings_get(conn, KEY_PLAYBACK_PASSPHRASE))
            .flatten()
            .filter(|s| !s.is_empty()),
        pbkeylen: PBKEYLEN,
    }
}

/// Enable or disable SRT encryption in the DB. On the first enable it generates
/// and stores a passphrase for each leg (reused thereafter, so re-enabling keeps
/// the same secret). Disabling keeps the stored passphrases but flips the flag,
/// which [`resolve`] turns into `None` passphrases.
pub fn set_enabled(conn: &rusqlite::Connection, enabled: bool) -> Result<(), rusqlite::Error> {
    if enabled {
        for key in [KEY_INGEST_PASSPHRASE, KEY_PLAYBACK_PASSPHRASE] {
            let existing = cred::settings_get(conn, key).filter(|s| !s.is_empty());
            if existing.is_none() {
                cred::settings_set(conn, key, &gen_passphrase())?;
            }
        }
    }
    cred::settings_set(conn, KEY_ENABLED, if enabled { "1" } else { "0" })
}

/// Path of the env file OME's `ome_start.sh` wrapper sources at startup.
fn env_file_path(data_path: &str) -> String {
    format!("{}/srt.env", data_path)
}

/// Write `<data>/srt.env` reflecting `eff`, atomically and `0600` (it holds the
/// passphrase). Empty passphrases mean encryption off — OME's `${env:...}`
/// default. `ome_start.sh` sources this; generated passphrases are hex, but the
/// values are single-quoted defensively so sourcing stays safe regardless.
pub fn write_env_file(data_path: &str, eff: &EffectiveSrt) -> std::io::Result<()> {
    let ingest = eff.ingest_passphrase.as_deref().unwrap_or("");
    let playback = eff.playback_passphrase.as_deref().unwrap_or("");
    let body = format!(
        "# Generated by the backend (gh #208). Sourced by ome_start.sh.\n\
         export SRT_INGEST_PASSPHRASE={}\n\
         export SRT_PLAYBACK_PASSPHRASE={}\n\
         export SRT_PBKEYLEN={}\n",
        sh_squote(ingest),
        sh_squote(playback),
        eff.pbkeylen,
    );

    let path = env_file_path(data_path);
    if let Some(parent) = std::path::Path::new(&path).parent() {
        std::fs::create_dir_all(parent)?;
    }
    let tmp = format!("{}.tmp", path);
    {
        let mut f = std::fs::OpenOptions::new()
            .write(true)
            .create(true)
            .truncate(true)
            .mode(0o600)
            .open(&tmp)?;
        f.write_all(body.as_bytes())?;
        f.sync_all()?;
    }
    std::fs::rename(&tmp, &path)
}

/// POSIX single-quote a string for safe `source`ing (`'` → `'\''`).
fn sh_squote(s: &str) -> String {
    format!("'{}'", s.replace('\'', "'\\''"))
}

/// Restart the OME supervisor program so it re-reads `srt.env`. No-op when
/// `STREAM_DISABLE_OME_RESTART` is set (integration tests) or when `supervisorctl`
/// is unavailable (dev outside the container) — the DB state is already persisted,
/// so the change applies on the next OME start regardless.
pub fn restart_ome() {
    if std::env::var("STREAM_DISABLE_OME_RESTART").is_ok() {
        tracing::debug!("[srt] OME restart skipped (STREAM_DISABLE_OME_RESTART)");
        return;
    }
    match std::process::Command::new("supervisorctl")
        .args([
            "-c",
            "/etc/supervisor/conf.d/supervisord.conf",
            "restart",
            "ome",
        ])
        .output()
    {
        Ok(o) if o.status.success() => {
            tracing::info!("[srt] restarted OME to apply SRT encryption change")
        }
        Ok(o) => tracing::error!(
            "[srt] `supervisorctl restart ome` failed: {}",
            String::from_utf8_lossy(&o.stderr).trim()
        ),
        Err(e) => tracing::error!("[srt] could not run supervisorctl: {e}"),
    }
}

/// Startup hook: write `srt.env` from the current DB state so the OME process —
/// which starts after the backend — reads the current passphrase.
pub fn init_startup(conn: &rusqlite::Connection, data_path: &str) {
    let eff = resolve(conn);
    if let Err(e) = write_env_file(data_path, &eff) {
        tracing::error!("[srt] failed to write srt.env: {e}");
    }
}

/// Shared JSON body for the admin `srt-config` GET and `srt-encryption` POST.
pub fn to_json(eff: &EffectiveSrt) -> serde_json::Value {
    serde_json::json!({
        "enabled": eff.enabled,
        "ingestPassphrase": eff.ingest_passphrase,
        "playbackPassphrase": eff.playback_passphrase,
        "pbkeylen": eff.pbkeylen,
    })
}

/// Apply a toggle: persist the flag (generating passphrases on first enable),
/// rewrite `srt.env`, and return the new effective config. The caller restarts
/// OME (kept separate so it can run outside the DB critical section).
pub fn apply_toggle(
    conn: &rusqlite::Connection,
    data_path: &str,
    enabled: bool,
) -> Result<EffectiveSrt, AppError> {
    set_enabled(conn, enabled).map_err(|e| AppError::Internal(e.to_string()))?;
    let eff = resolve(conn);
    write_env_file(data_path, &eff).map_err(|e| AppError::Internal(e.to_string()))?;
    Ok(eff)
}
